// Code is generated by github.com/swaggest/swac <version>, do not edit. 🤖

/**
 * @typedef ExamplesAdvancedDirectGzipRequest
 * @type {object}
 * @property {boolean} plainStruct - Output plain structure instead of gzip container.
 * @property {boolean} countItems - Invokes internal decoding of compressed data.
 */

/**
 * @typedef AdvancedGzipPassThroughStruct
 * @type {object}
 * @property {number} id.
 * @property {array<string>} text.
 */

/**
 * @callback AdvancedGzipPassThroughStructCallback
 * @param {AdvancedGzipPassThroughStruct} value
 */

/**
 * @typedef HeadGzipPassThroughRequest
 * @type {object}
 * @property {boolean} plainStruct - Output plain structure instead of gzip container.
 * @property {boolean} countItems - Invokes internal decoding of compressed data.
 */

/**
 * @callback RawCallback
 * @param {XMLHttpRequest} value
 */

/**
 * @typedef AdvancedInputWithJSONType3
 * @type {object}
 * @property {number} id.
 * @property {string} name.
 */

/**
 * @typedef PostJsonBodyValidationInPathRequest
 * @type {object}
 * @property {number} inQuery - Simple scalar value in query.
 * @property {string} inPath - Simple scalar value in path.
 * @property {string} xHeader - Simple scalar value in header.
 * @property {AdvancedInputWithJSONType3} body.
 */

/**
 * @typedef AdvancedOutputWithJSONType3
 * @type {object}
 * @property {number} id.
 * @property {string} inHeader.
 * @property {string} inPath.
 * @property {number} inQuery.
 * @property {string} name.
 */

/**
 * @callback AdvancedOutputWithJSONType3Callback
 * @param {AdvancedOutputWithJSONType3} value
 */

/**
 * @typedef AdvancedInputWithJSONType2
 * @type {object}
 * @property {number} id.
 * @property {string} name.
 */

/**
 * @typedef PostJsonBodyInPathRequest
 * @type {object}
 * @property {string} inQuery - Simple scalar value in query.
 * @property {string} inPath - Simple scalar value in path.
 * @property {string} xHeader - Simple scalar value in header.
 * @property {AdvancedInputWithJSONType2} body.
 */

/**
 * @typedef AdvancedOutputWithJSONType2
 * @type {object}
 * @property {number} id.
 * @property {string} inHeader.
 * @property {string} inPath.
 * @property {string} inQuery.
 * @property {string} name.
 */

/**
 * @callback AdvancedOutputWithJSONType2Callback
 * @param {AdvancedOutputWithJSONType2} value
 */

/**
 * @typedef PostJsonMapBodyRequest
 * @type {object}
 * @property {number} inQuery - Simple scalar value in query.
 * @property {string} xHeader - Simple scalar value in header.
 * @property {object<string, number>} body.
 */

/**
 * @typedef AdvancedJsonOutputType2
 * @type {object}
 * @property {object<string, number>} data.
 * @property {string} inHeader.
 * @property {number} inQuery.
 */

/**
 * @callback AdvancedJsonOutputType2Callback
 * @param {AdvancedJsonOutputType2} value
 */

/**
 * JSON value in query
 * @typedef AdvancedJSONPayload
 * @type {object}
 * @property {number} id.
 * @property {string} name.
 */

/**
 * @typedef GetJsonParamInPathRequest
 * @type {object}
 * @property {number} inQuery - Simple scalar value in query.
 * @property {AdvancedJSONPayload} identity - JSON value in query.
 * @property {string} inPath - Simple scalar value in path.
 * @property {string} xHeader - Simple scalar value in header.
 */

/**
 * @typedef AdvancedOutputWithJSON
 * @type {object}
 * @property {number} id.
 * @property {string} inHeader.
 * @property {string} inPath.
 * @property {number} inQuery.
 * @property {string} name.
 */

/**
 * @callback AdvancedOutputWithJSONCallback
 * @param {AdvancedOutputWithJSON} value
 */

/**
 * @typedef PostJsonSliceBodyRequest
 * @type {object}
 * @property {number} inQuery - Simple scalar value in query.
 * @property {string} xHeader - Simple scalar value in header.
 * @property {array<number>} body.
 */

/**
 * @typedef AdvancedJsonOutput
 * @type {object}
 * @property {array<number>} data.
 * @property {string} inHeader.
 * @property {number} inQuery.
 */

/**
 * @callback AdvancedJsonOutputCallback
 * @param {AdvancedJsonOutput} value
 */

/**
 * @typedef RestErrResponse
 * @type {object}
 * @property {number} code - Application-specific error code.
 * @property {object<string, *>} context - Application context.
 * @property {string} error - Error message.
 * @property {string} status - Status text.
 */

/**
 * @callback RestErrResponseCallback
 * @param {RestErrResponse} value
 */

/**
 * @typedef AdvancedHeaderOutput
 * @type {object}
 * @property {string} inBody.
 */

/**
 * @callback AdvancedHeaderOutputCallback
 * @param {AdvancedHeaderOutput} value
 */

/**
 * @typedef GetQueryObjectRequest
 * @type {object}
 * @property {object<string, number>} inQuery - Object value in query.
 */

/**
 * @typedef AdvancedOutputQueryObject
 * @type {object}
 * @property {object<string, number>} inQuery.
 */

/**
 * @callback AdvancedOutputQueryObjectCallback
 * @param {AdvancedOutputQueryObject} value
 */

/**
 * @typedef PostReqRespMappingRequest
 * @type {object}
 * @property {string} xHeader - Simple scalar value.
 * @property {number} val2 - Simple scalar value.
 */

/**
 * @typedef AdvancedInputPortType2Data
 * @type {object}
 * @property {string} value - Request minLength: 3, response maxLength: 7.
 */

/**
 * @typedef AdvancedInputPortType2
 * @type {object}
 * @property {AdvancedInputPortType2Data} data.
 */

/**
 * @typedef PostValidationRequest
 * @type {object}
 * @property {boolean} q - This parameter will bypass explicit validation as it does not have constraints.
 * @property {number} xInput - Request minimum: 10, response maximum: 20.
 * @property {AdvancedInputPortType2} body.
 */

/**
 * @typedef AdvancedOutputPortType2Data
 * @type {object}
 * @property {string} value.
 */

/**
 * @typedef AdvancedOutputPortType2
 * @type {object}
 * @property {AdvancedOutputPortType2Data} data.
 */

/**
 * @callback AdvancedOutputPortType2Callback
 * @param {AdvancedOutputPortType2} value
 */

