/* tslint:disable */
/* eslint-disable */
// Code is generated by github.com/swaggest/swac <version>, DO NOT EDIT. 🤖

/**
 * @typedef XhAggregatorAddress
 * @type {object}
 * @property {number} end - Interval end UTC unix timestamp. .
 * @property {string} id - Profile ID.
 * @property {object<string, string>} labels.
 * @property {number} start - Interval start UTC unix timestamp.
 */

/**
 * @typedef XhUsecaseProfileInfo
 * @type {object}
 * @property {XhAggregatorAddress} addr.
 * @property {string} cpu.
 * @property {number} edges.
 * @property {string} io.
 * @property {string} peakMem.
 * @property {number} profiles.
 * @property {string} wt.
 */

/**
 * @typedef XhUsecaseProfiles
 * @type {object}
 * @property {array<XhUsecaseProfileInfo>} activeAggregates.
 * @property {array<XhUsecaseProfileInfo>} recent.
 */

/**
 * @callback XhUsecaseProfilesCallback
 * @param {XhUsecaseProfiles} value
 */

/**
 * @typedef XhProfileValue
 * @type {object}
 * @property {number} as - Aggregation size, count of parent profiles.
 * @property {number} cpu - CPU time in microseconds.
 * @property {number} ct - Count of calls.
 * @property {number} io - IO time in microseconds.
 * @property {number} mem.aa - The amount of allocated memory.
 * @property {number} mem.na - The sum of the number of all allocations in this function.
 * @property {number} mem.nf - The sum of the number of all frees in this function.
 * @property {number} mu - Memory usage in bytes.
 * @property {number} pmu - Peak memory usage in bytes.
 * @property {number} wt - Wall time in microseconds.
 */

/**
 * @typedef XhUsecaseCollectProfileInput
 * @type {object}
 * @property {string} id - Random string created by client to identify profile.
 * @property {object<string, string>} labels.
 * @property {object<string, *>} meta - Additional context.
 * @property {object<string, XhProfileValue>} profile.
 */

/**
 * @typedef XhPostProfileRequest
 * @type {object}
 * @property {number} probability - Probability that was asserted to collect this profile, used to estimate total multiplication.
 * @property {string} tz - Timezone location for daily aggregations, default: UTC.
 * @property {XhUsecaseCollectProfileInput} body.
 */

/**
 * @callback RawCallback
 * @param {XMLHttpRequest} value
 */

/**
 * @typedef XhGetProfileDotRequest
 * @type {object}
 * @property {string} rootSymbol.
 * @property {number} graphLimit - Maximum number of nodes (symbols) in graph.
 * @property {('wt'|'cpu'|'io')} graphPriority - Graph resource determines nodes selection to expose strongest contributors.
 * @property {XhAggregatorAddress} aggregate.
 */

/**
 * @typedef XhRestErrResponse
 * @type {object}
 * @property {number} code - Application-specific error code.
 * @property {object<string, *>} context - Application context.
 * @property {string} error - Error message.
 * @property {string} status - Status text.
 */

/**
 * @callback XhRestErrResponseCallback
 * @param {XhRestErrResponse} value
 */

/**
 * @typedef XhGetProfileFindSymbolRequest
 * @type {object}
 * @property {XhAggregatorAddress} aggregate.
 * @property {string} match - Substring to match in symbol.
 * @property {number} limit - Limit number of results.
 */

/**
 * @typedef XhUsecaseSearchOutput
 * @type {object}
 * @property {array<string>} symbols.
 */

/**
 * @callback XhUsecaseSearchOutputCallback
 * @param {XhUsecaseSearchOutput} value
 */

/**
 * @typedef XhGetProfileSymbolRequest
 * @type {object}
 * @property {XhAggregatorAddress} aggregate.
 * @property {string} symbol.
 */

/**
 * @typedef XhRenderValueStat
 * @type {object}
 * @property {string} as.
 * @property {string} cpu.
 * @property {string} cpuf.
 * @property {string} ct.
 * @property {string} ctf.
 * @property {string} io.
 * @property {string} iof.
 * @property {string} ma.
 * @property {string} mac.
 * @property {string} mf.
 * @property {string} mu.
 * @property {string} pmu.
 * @property {string} wt.
 * @property {string} wtf.
 */

/**
 * @typedef XhUsecaseSymbolStatOutput
 * @type {object}
 * @property {object<string, XhRenderValueStat>} callees - Callees stat.
 * @property {object<string, XhRenderValueStat>} callers - Callers stat.
 * @property {XhRenderValueStat} exclusive.
 * @property {XhRenderValueStat} inclusive.
 */

/**
 * @callback XhUsecaseSymbolStatOutputCallback
 * @param {XhUsecaseSymbolStatOutput} value
 */

/**
 * @typedef XhGetTopTracesRequest
 * @type {object}
 * @property {string} rootSymbol.
 * @property {XhAggregatorAddress} aggregate.
 * @property {('wt'|'cpu'|'io')} resource - Graph resource determines nodes selection to expose strongest contributors.
 * @property {number} limit.
 */

/**
 * @typedef XhUsecaseTraceInfo
 * @type {object}
 * @property {string} hash.
 * @property {XhRenderValueStat} stat.
 * @property {string} symbol.
 * @property {array<string>} trace.
 */

/**
 * @callback ArrayXhUsecaseTraceInfoCallback
 * @param {array<XhUsecaseTraceInfo>} value
 */

