// Code generated by github.com/swaggest/swac <version>, DO NOT EDIT.

package acme

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"io/ioutil"
	"net/http"
)

// PostPartnerWebhookURLRequest is operation request value.
type PostPartnerWebhookURLRequest struct {
	Body         *WebhookPayload                                 // Body is a JSON request body.
	// XIWEventType is a required `X-IW-Event-Type` parameter in header.
	// The event type sent by iwoca.
	XIWEventType PostPartnerWebhookURLRequestHeaderXIWEventType
	// XIWEventID is a required `X-IW-Event-ID` parameter in header.
	// The event id sent by iwoca.
	XIWEventID   string
	// XIWSignature is a required `X-IW-Signature` parameter in header.
	// HMAC hex digest of the payload.
	XIWSignature string
}

// encode creates *http.Request for request data.
func (request *PostPartnerWebhookURLRequest) encode(ctx context.Context, baseURL string) (*http.Request, error) {
	requestURI := baseURL + "/partner_webhook_url/"

	body, err := json.Marshal(request.Body)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, requestURI, bytes.NewBuffer(body))
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", "application/json")

	req.Header.Set("X-IW-Event-Type", string(request.XIWEventType))

	req.Header.Set("X-IW-Event-ID", request.XIWEventID)

	req.Header.Set("X-IW-Signature", request.XIWSignature)

	req = req.WithContext(ctx)

	return req, err
}

// PostPartnerWebhookURLResponse is operation response value.
type PostPartnerWebhookURLResponse struct {
	StatusCode int
	RawBody    []byte  // RawBody contains read bytes of response body.
}

// decode loads data from *http.Response.
func (result *PostPartnerWebhookURLResponse) decode(resp *http.Response) error {
	var err error

	dump := bytes.NewBuffer(nil)
	body := io.TeeReader(resp.Body, dump)

	result.StatusCode = resp.StatusCode

	switch resp.StatusCode {
	case http.StatusCreated:
		// No body to decode.
	default:
		_, readErr := ioutil.ReadAll(body)
		if readErr != nil {
			err = errors.New("unexpected response status: " + resp.Status +
				", could not read response body: " + readErr.Error())
		} else {
			err = errors.New("unexpected response status: " + resp.Status)
		}
	}

	result.RawBody = dump.Bytes()

	if err != nil {
		return responseError{
			resp: resp,
			body: dump.Bytes(),
			err:  err,
		}
	}

	return nil
}

// PostPartnerWebhookURL performs REST operation.
func (c *Client) PostPartnerWebhookURL(ctx context.Context, request PostPartnerWebhookURLRequest) (result PostPartnerWebhookURLResponse, err error) {
	if c.InstrumentCtxFunc != nil {
		ctx = c.InstrumentCtxFunc(ctx, http.MethodPost, "/partner_webhook_url/", &request)
	}

	if c.Timeout != 0 {
		var cancel func()
		ctx, cancel = context.WithTimeout(ctx, c.Timeout)

		defer cancel()
	}

	req, err := request.encode(ctx, c.BaseURL)
	if err != nil {
		return result, err
	}

	resp, err := c.transport.RoundTrip(req)

	if err != nil {
		return result, err
	}

	defer func() {
		closeErr := resp.Body.Close()
		if closeErr != nil && err == nil {
			err = closeErr
		}
	}()

	err = result.decode(resp)

	return result, err
}
