// Code is generated by github.com/swaggest/swac <version>, do not edit. 🤖

/**
 * @constructor
 * @param {string} baseURL - Base URL.
 */
function FooClient(baseURL) {
    // Trim trailing backslash.
    this.baseURL = (baseURL.charAt(baseURL.length - 1) === '/') ? baseURL.slice(0, -1) : baseURL;
}

/**
 * @param {object} req
 * @param {cbDataSetList} onOK
 */
FooClient.prototype.listDataSets = function (req, onOK) {
    var x = new XMLHttpRequest();
    x.onreadystatechange = function () {
        if (x.readyState !== XMLHttpRequest.DONE) {
            return
        }
    
        switch (x.status) {
            case 200:
                if (typeof(onOK) == 'function') {
                    onOK(JSON.parse(x.responseText));
                }
                break;
            default:
                throw {err: 'unexpected response', data: x}
        }
    };
    
    var url = this.baseURL + '/?';
    url = url.slice(0, -1)

    x.open("GET", url, true);
    
    
    x.send();
}

/**
 * @param {GetDatasetVersionFieldsRequest} req
 * @param {cbString} onOK
 * @param {cbString} onNotFound
 */
FooClient.prototype.getDatasetVersionFields = function (req, onOK, onNotFound) {
    var x = new XMLHttpRequest();
    x.onreadystatechange = function () {
        if (x.readyState !== XMLHttpRequest.DONE) {
            return
        }
    
        switch (x.status) {
            case 200:
                if (typeof(onOK) == 'function') {
                    onOK(JSON.parse(x.responseText));
                }
                break;
            case 404:
                if (typeof(onNotFound) == 'function') {
                    onNotFound(JSON.parse(x.responseText));
                }
                break;
            default:
                throw {err: 'unexpected response', data: x}
        }
    };
    
    var url = this.baseURL + '/' + encodeURIComponent(req.dataset) +
    '/' + encodeURIComponent(req.version) +
    '/fields?';
    url = url.slice(0, -1)

    x.open("GET", url, true);
    
    
    x.send();
}

/**
 * @param {PostDatasetVersionRecordsRequest} req
 * @param {cbArrayObjectStringObject} onOK
 * @param {cbEmpty} onNotFound
 */
FooClient.prototype.postDatasetVersionRecords = function (req, onOK, onNotFound) {
    var x = new XMLHttpRequest();
    x.onreadystatechange = function () {
        if (x.readyState !== XMLHttpRequest.DONE) {
            return
        }
    
        switch (x.status) {
            case 200:
                if (typeof(onOK) == 'function') {
                    onOK(JSON.parse(x.responseText));
                }
                break;
            case 404:
                if (typeof(onNotFound) == 'function') {
                    onNotFound(JSON.parse(x.responseText));
                }
                break;
            default:
                throw {err: 'unexpected response', data: x}
        }
    };
    
    var url = this.baseURL + '/' + encodeURIComponent(req.dataset) +
    '/' + encodeURIComponent(req.version) +
    '/records?';
    url = url.slice(0, -1)

    x.open("POST", url, true);
    
    
    x.send();
}

