/* tslint:disable */
/* eslint-disable */
// Code is generated by github.com/swaggest/swac <version>, DO NOT EDIT. 🤖

/**
 * @typedef DataSetListApisItems
 * @type {Object}
 * @property {String} apiKey - To be used as a dataset parameter value.
 * @property {String} apiVersionNumber - To be used as a version parameter value.
 * @property {String} apiUrl - The URL describing the dataset's fields.
 * @property {String} apiDocumentationUrl - A URL to the API console for each API.
 */

/**
 * @typedef DataSetList
 * @type {Object}
 * @property {Number} total
 * @property {Array<DataSetListApisItems>} apis
 */

/**
 * @callback DataSetListCallback
 * @param {DataSetList} value
 */

/**
 * @typedef GetDatasetVersionFieldsRequest
 * @type {Object}
 * @property {String} dataset - Name of the dataset.
 * @property {String} version - Version of the dataset.
 */

/**
 * @callback StringCallback
 * @param {String} value
 */

/**
 * @typedef PostDatasetVersionRecordsRequest
 * @type {Object}
 * @property {String} version - Version of the dataset.
 * @property {String} dataset - Name of the dataset. In this case, the default value is oa_citations.
 * @property {String} criteria - Uses Lucene Query Syntax in the format of propertyName:value, propertyName:[num1 TO num2] and date range format: propertyName:[yyyyMMdd TO yyyyMMdd]. In the response please see the 'docs' element which has the list of record objects. Each record structure would consist of all the fields and their corresponding values.
 * @property {Number} start - Starting record number. Default value is 0.
 * @property {Number} rows - Specify number of rows to be returned. If you run the search with default values, in the response you will see 'numFound' attribute which will tell the number of records available in the dataset.
 */

/**
 * @callback ArrayObjectStringObjectCallback
 * @param {Array<Object.<String,Object>>} value
 */

/**
 * @callback RawCallback
 * @param {XMLHttpRequest} value
 */

