// Code is generated by github.com/swaggest/swac <version>, DO NOT EDIT. 🤖

/**
 * @typedef FindPetsRequest
 * @type {Object}
 * @property {Array<String>} tags - tags to filter by.
 * @property {Number} limit - maximum number of results to return.
 */

/**
 * @typedef NewPet
 * @type {Object}
 * @property {String} name
 * @property {String} tag
 */

/**
 * @typedef PetAllOf1
 * @type {Object}
 * @property {Number} id
 */

/**
 * @callback ArrayNewPetPetAllOf1Callback
 * @param {Array<NewPet|PetAllOf1>} value
 */

/**
 * @typedef PostPetsRequest
 * @type {Object}
 * @property {NewPet} body
 */

/**
 * @callback NewPetPetAllOf1Callback
 * @param {NewPet|PetAllOf1} value
 */

/**
 * @typedef GetPetsIdRequest
 * @type {Object}
 * @property {Number} id - ID of pet to fetch.
 */

/**
 * @typedef DeletePetsIdRequest
 * @type {Object}
 * @property {Number} id - ID of pet to delete.
 */

/**
 * @callback RawCallback
 * @param {XMLHttpRequest} value
 */

