// Code is generated by github.com/swaggest/swac <version>, do not edit. 🤖

/**
 * @typedef FindPetsRequest
 * @type {object}
 * @property {array<string>} tags.
 * @property {number} limit.
 */

/**
 * @typedef NewPet
 * @type {object}
 * @property {string} name.
 * @property {string} tag.
 */

/**
 * @typedef PetAllOf1
 * @type {object}
 * @property {number} id.
 */

/**
 * @callback ArrayNewPetPetAllOf1Callback
 * @param {array<NewPet|PetAllOf1>} value
 */

/**
 * @typedef PostPetsRequest
 * @type {object}
 * @property {NewPet} body.
 */

/**
 * @callback NewPetPetAllOf1Callback
 * @param {NewPet|PetAllOf1} value
 */

/**
 * @typedef GetPetsIdRequest
 * @type {object}
 * @property {number} id.
 */

/**
 * @typedef DeletePetsIdRequest
 * @type {object}
 * @property {number} id.
 */

/**
 * @callback RawCallback
 * @param {XMLHttpRequest} value
 */

