// Code generated by github.com/swaggest/swac v0.0.3, DO NOT EDIT.

// Package uspto contains autogenerated REST client.
package uspto

import (
	"net/http"
	"time"
)

// DefaultBaseURL is the default base URL for this service.
const DefaultBaseURL = "{scheme}://developer.uspto.gov/ds-api"

// Client is a REST service HTTP client.
type Client struct {
	BaseURL   string
	Timeout   time.Duration
	transport http.RoundTripper
}

// NewClient creates client instance with default transport.
func NewClient() *Client {
	return &Client{
		transport: http.DefaultTransport,
		Timeout:   30 * time.Second,
		BaseURL:   DefaultBaseURL,
	}
}

// SetTransport sets client transport.
func (c *Client) SetTransport(transport http.RoundTripper) {
	c.transport = transport

}
