// Code generated by github.com/swaggest/swac <version>, DO NOT EDIT.

package uspto

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
)

// ListSearchableFieldsRequest is operation request value.
type ListSearchableFieldsRequest struct {
	// Dataset is a required `dataset` parameter in path.
	// Name of the dataset.
	Dataset string
	// Version is a required `version` parameter in path.
	// Version of the dataset.
	Version string
}

// encode creates *http.Request for request data.
func (request *ListSearchableFieldsRequest) encode(ctx context.Context, baseURL string) (*http.Request, error) {
	requestURI := baseURL + "/" + url.PathEscape(request.Dataset) + "/" + url.PathEscape(request.Version) + "/fields"

	req, err := http.NewRequest(http.MethodGet, requestURI, nil)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Accept", "application/json")

	req = req.WithContext(ctx)

	return req, err
}

// ListSearchableFieldsResponse is operation response value.
type ListSearchableFieldsResponse struct {
	StatusCode    int
	RawBody       []byte  // RawBody contains read bytes of response body.
	ValueOK       string  // ValueOK is a value of 200 OK response.
	ValueNotFound string  // ValueNotFound is a value of 404 Not Found response.
}

// decode loads data from *http.Response.
func (result *ListSearchableFieldsResponse) decode(resp *http.Response) error {
	var err error

	dump := bytes.NewBuffer(nil)
	body := io.TeeReader(resp.Body, dump)

	result.StatusCode = resp.StatusCode

	switch resp.StatusCode {
	case http.StatusOK:
		err = json.NewDecoder(body).Decode(&result.ValueOK)
	case http.StatusNotFound:
		err = json.NewDecoder(body).Decode(&result.ValueNotFound)
	default:
		_, readErr := ioutil.ReadAll(body)
		if readErr != nil {
			err = errors.New("unexpected response status: " + resp.Status +
				", could not read response body: " + readErr.Error())
		} else {
			err = errors.New("unexpected response status: " + resp.Status)
		}
	}

	result.RawBody = dump.Bytes()

	if err != nil {
		return responseError{
			resp: resp,
			body: dump.Bytes(),
			err:  err,
		}
	}

	return nil
}

// ListSearchableFields performs REST operation.
func (c *Client) ListSearchableFields(ctx context.Context, request ListSearchableFieldsRequest) (result ListSearchableFieldsResponse, err error) {
	if c.InstrumentCtxFunc != nil {
		ctx = c.InstrumentCtxFunc(ctx, http.MethodGet, "/{dataset}/{version}/fields", &request)
	}

	if c.Timeout != 0 {
		var cancel func()
		ctx, cancel = context.WithTimeout(ctx, c.Timeout)

		defer cancel()
	}

	req, err := request.encode(ctx, c.BaseURL)
	if err != nil {
		return result, err
	}

	resp, err := c.transport.RoundTrip(req)

	if err != nil {
		return result, err
	}

	defer func() {
		closeErr := resp.Body.Close()
		if closeErr != nil && err == nil {
			err = closeErr
		}
	}()

	err = result.decode(resp)

	return result, err
}
